- id: fixit-lint
  name: Fixit - lint
  description: This hook shows Fixit lints and suggested changes without applying autofixes.
  entry: fixit lint --diff
  language: python
  types: [python]
- id: fixit-fix
  name: Fixit - lint and apply autofixes
  description: This hook shows Fixit lints and applies suggested changes.
  entry: fixit fix --automatic
  language: python
  types: [python]
